# Site settings  
title: "Your Paper Title"  
description: "A brief description of your paper"  
url: "https://yourusername.github.io/yourrepository"  
baseurl: ""  
permalink: /:title/  
  
# Author information  
author:  
  name: "Your Name"  
  email: "your.email@example.com"  
  github: "https://github.com/yourusername"  
  linkedin: "https://www.linkedin.com/in/yourusername"  
  
# Build settings  
markdown: kramdown  
theme: minima  
plugins:  
  - jekyll-feed  
  - jekyll-seo-tag  
  
# Exclude unnecessary files  
exclude:  
  - Gemfile  
  - Gemfile.lock  
  - node_modules  
  - vendor/bundle/  
  - vendor/cache/  
  - vendor/gems/  
  - vendor/ruby/  
  
# Navigation settings  
header_pages:  
  - diffcolor.md  
  
# Google Analytics (optional)  
google_analytics: "your-tracking-id"  
